### ISSUE TITLE
Failure in Kobocoinj - Not connecting correctly to blockchain

### ISSUE THREAD

**Issue by kobocoin** [machado-rev/kobocoinj#1]
I am receiving the following error when trying to compile my Android wallet. This error is coming from the kobocoinj. I have edited the following files correctly I believe:

##### ValidHashStore.java

This is the failure when compiling the wallet

### Wallet Test Failure Message

Running com.machadocrypto.kobocoin_android_wallet.util.BluetoothTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 sec - in com.machadocrypto.kobocoin_android_wallet.util.BluetoothTest
Running com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec <<< FAILURE! - in com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest
formatMKOBOValue(com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest)  Time elapsed: 0.032 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[200]0000000000.00> but was:<[35]0000000000.00>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest.formatMKOBOValue(GenericUtilsTest.java:75)

formatUKOBOValue(com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[200]0000000000000> but was:<[35]0000000000000>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest.formatUKOBOValue(GenericUtilsTest.java:97)

formatValue(com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[200]0000000.00> but was:<[35]0000000.00>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.machadocrypto.kobocoin_android_wallet.util.GenericUtilsTest.formatValue(GenericUtilsTest.java:53)

Running com.machadocrypto.kobocoin_android_wallet.util.Base43Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.machadocrypto.kobocoin_android_wallet.util.Base43Test
Running com.machadocrypto.kobocoin_android_wallet.util.CryptoTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.254 sec - in com.machadocrypto.kobocoin_android_wallet.util.CryptoTest

#### Tests run: 13, Failures: 3, Errors: 0, Skipped: 0

I need to know is how to manipulate the numbers in the failure results above. I believe that once I can manipulate the error message I know I'm at least in the right ball park. At the moment nothing I do is causing any change in the error message.

I have learnt how to calculate Little Endian number precisely for ValidHashStore.java so that may not be the issue.

**Comment by machado-rev** [comment]
This I think that is easy to solve I THINK! I am working on confirmation issue on the wallet here https://github.com/MatthewLM/peercoinj/issues/1

and will test to you right?

**Comment by kobocoin** [comment]
Just seen the post. I'll follow it. I see what you mean by coinbase issues.

**Comment by kobocoin** [comment]
This was caused by the MAX_MONEY parameter in NetworkParameters.java

**Comment by MatthewLM** [comment]
For new coins you have the choice to remove all unit tests, or do a lot of work modifying them. A large amount of the unit tests will depend on coin parameters and so need to be changed.

**Comment by kobocoin** [comment]
Maybe I'm missing something, but the junit tests aren't really tests. They're just comparing a hardcoded number in one file with hardcoded values in another file. Or is there a test run in the background against the blockchain that I'm not aware of? 

In resolving this I found I was able to make all values whatever arbitrary figure I came up with. I'm aware that MAX_MONEY restricts user entry to a maximum equal to the max number of coins, but I thought there was some form of test against the blockchain. It appears that's not the case, or am I mistaken?

**Comment by machado-rev** [comment]
I am looking here on the code, today I will do a reply, maybe it's simple!

**Comment by MatthewLM** [comment]
Many tests have nothing to do with the blockchain. There are a lot of formatting tests, which need to be changed.

**Comment by machado-rev** [comment]
I made the coin workin @MatthewLM for kobocoin, updated with fix the issue of disconnect blockchain. I will need help only to format money on sending purpose, like send 10 coins, he are sending 0.1, but this case are done, we can close this issue.
I will update the code in github soon as I can.
